#!/bin/sh
# Builds the Cloudflare Pages Functions from the Netlify function sources (one codebase, two hosts).
set -e
cd "$(dirname "$0")/.."
{
cat <<'H'
// GENERATED by scripts/gen-cf.sh from netlify/functions/shop.mjs. Do not edit by hand.
import { getStore as d1Store, init } from '../_d1store.js'
let DB
const getStore = () => d1Store(DB)
H
sed -e "/^import { getStore } from '@netlify\/blobs'/d" -e "s/getStore({ name: 'dukaan', consistency: 'strong' })/getStore()/" -e "s/x-nf-client-connection-ip/cf-connecting-ip/" -e "s/^export default async (req) => {/const run = async (req) => {/" netlify/functions/shop.mjs
cat <<'T'
export async function onRequest({ request, env }) {
  DB = env.DB
  if (!DB) return new Response(JSON.stringify({ error: 'DB binding missing' }), { status: 500, headers: { 'content-type': 'application/json' } })
  await init(DB)
  return run(request)
}
T
} > functions/api/shop.js
{
echo "// GENERATED by scripts/gen-cf.sh from netlify/functions/agent.mjs. Do not edit by hand."
sed -e "s/^export default async (req) => {/const run = async (req) => {/" netlify/functions/agent.mjs
cat <<'T'
export async function onRequest({ request }) { return run(request) }
T
} > functions/api/agent.js
